[package]
name = "bevy_dui"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.79"
bevy = "0.12"
quick-xml = "0.31"
bevy_ecss = { git = "https://github.com/robtfm/bevy_ecss", branch = "main-12" }
